language: node_js
node_js:
  - '10'
  - '8'
  - '6'
install:
- npm install -g markdownlint-cli
script:
- markdownlint --config .markdownlint.yml *.md
- bash -c 'shopt -s globstar; shellcheck **/*.{sh}'
- npm test
